apiVersion: v1
kind: PersistentVolume
metadata:
#  namespace: nginx-ingress
  name: nfs-pv
  labels:
    name: nfs-pv
    env: dev
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  claimRef:
    name: nfs-pv-claim
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: nginx-ingress
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/xgrid_pods_info
    server: 192.168.0.9
