apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Mi
  storageClassName: slow
  selector:
    matchLabels:
      name: "nfs-pv"
    matchExpressions:
      - {key: env, operator: In, values: [dev]}
