apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-claim
  namespace: nginx-ingress
spec:
  accessModes:
    - ReadWriteMany
#  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Mi
#  storageClassName: slow
  volumeName: nfs-pv
  selector:
    matchLabels:
      name: "nfs-pv"
    matchExpressions:
      - {key: env, operator: In, values: [dev]}
